[package]
name = "sha256sum"
version = "0.1.0"
edition = "2021"
description = "Generate checksum of a file with the SHA256 algorithm" 
author = ["Devdutt Shenoi<devdutt@outlook.in>"]
license-file = "LICENSE"

[dependencies]
sha2 = "0.10.8"
structopt = "0.3.26"
